site_name: 'Jetstream2 Documentation'
site_url: https://docs.jetstream-cloud.org/
site_description: "Jetstream2 Documentation"
repo_url: https://github.com/jetstream-cloud/js2docs
copyright: Copyright Â© 2021 The Trustees of Indiana University
site_favicon: 'images/Jetstream2_icon_64px.jpg'

theme:
  name: "readthedocs"
  analytics:
    provider: google
    #OLD gtag: G-3KNR9L6H6Y
    gtag: G-PQH32H51WS
  google_analytics: ['UA-204881722-1', 'jetstream2wiki.readthedocs.io']
  prev_next_buttons_location: bottom
  # prev_next_buttons_location: none
  titles_only: True
  include_404: True
  collapse_navigation: True
  sticky_navigation: True
  #collapse_navigation: False
  #name: "windmill"
  #name: "material"
  #palette:
  #  primary: black
  #features:
  #  - navigation.top
  logo: 'images/jetstream-logo-white.svg'
  highlightjs: false
  style_external_links: True
  'display_version': False

extra_css:
    - 'css/custom.css'
    - 'css/cacao.css'

extra_javascript:
    - 'js/matomo.js'

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - attr_list
    - admonition

plugins:
    - search:
        indexing: 'full'

extra:
    consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

#google_analytics: ['UA-204881722-1','wiki.jetstream-cloud.org']
#https://github.com/mkdocs/mkdocs/issues/2101
#https://github.com/mkdocs/mkdocs/issues/1794

nav:
  - Jetstream2 Home: index.md
  - Migrating from Jetstream1 to Jetstream2: migrating.md
  - Jetstream2 Early Operations FAQ: faq/js2-earlyops-faq.md
  - Jetstream2 Info:
    - System Overview: overview/overview-doc.md
    - Key Differences Between Jetstream 1 and 2: overview/keydiff.md
    - Configuration and specifications: overview/config.md
    - Network configuration and considerations: overview/network.md
  - Frequently Asked Questions:
    - General FAQs: faq/general-faq.md
    - Troubleshooting: faq/trouble.md
    - Allocations: faq/alloc.md
    - Security: faq/security.md
    - Software: faq/software.md
  - General Usage Information:
    - Jetstream2 Resources: general/resources.md
    - Jetstream2 Storage: general/storage.md
    - XSEDE Service Units and Jetstream2: general/xsede.md
    - VM Sizes and Configurations: general/vmsizes.md
    - Featured Images: general/featured.md
    - Instance Management Actions: general/instancemgt.md
    - Jetstream2 Software Collection: general/software.md
    - Software Licenses: general/licenses.md
    - Policies and Best Practices:
      - Acceptable Usage Policies: general/policies.md
      - Export Control Guidance: general/export.md
      - AUPs for Jetstream2 Hosted Gateways: general/gateways.md
      - Best Practices: general/bestpractice.md
    - Microsoft Windows on Jetstream2: general/windows.md
  - Allocations:
    - Allocations Overview: alloc/overview.md
    - Trial Allocation: alloc/trial.md
    - Startup Allocations: alloc/startup.md
    - Education Allocations: alloc/education.md
    - Research Allocations: alloc/research.md
    - Supplements (Storage/SUs): alloc/supplement.md
    - Extensions & Renewals: alloc/extension.md
    - Frequently Asked Questions: alloc/faq.md
  - User Interfaces:
    - Exosphere:
      - Overview: ui/exo/exo.md
      - Logging In: ui/exo/login.md
      - Creating an Instance: ui/exo/create_instance.md
      - Instance Management: ui/exo/manage.md
      - Storage Under Exosphere: ui/exo/storage.md
      - Push-button clusters: ui/exo/push-button-cluster.md
      - Exosphere Troubleshooting: ui/exo/troubleshooting.md
    - Cacao (fka Atmosphere2):
      - Overview: ui/cacao/overview.md
      - What is Cacao: ui/cacao/intro.md
      - Glossary: ui/cacao/glossary.md
      - UI Basics: ui/cacao/ui_basics.md
      - Getting Started For New Cacao Users: ui/cacao/getting_started.md
      - Credentials: ui/cacao/credentials.md
      - Workspaces: ui/cacao/workspaces.md
      - Deployments (Launching a VM): ui/cacao/deployments.md
      - Choosing Your Allocation: ui/cacao/alloc.md
      - Logging Into An Instance: ui/cacao/login.md
      - Instance Management: ui/cacao/manage.md
      - Storage: ui/cacao/storage.md
      - Cacao Troubleshooting: ui/cacao/troubleshooting.md
    - Horizon:
      - Overview: ui/horizon/intro.md
      - Security Group Management: ui/horizon/security_group.md
      - Networks in Horizon: ui/horizon/network.md
      - Launching Instances: ui/horizon/launch.md
      - Instance Management: ui/horizon/manage.md
      - Volumes Under Horizon: ui/horizon/volumes.md
      - Manila Shares in Horizon: ui/horizon/manila.md
      - Horizon Troubleshooting: ui/horizon/troubleshooting.md
    - CLI:
      - Overview: ui/cli/overview.md
      - Installing Openstack Clients: ui/cli/clients.md
      - Setting up openrc.sh: ui/cli/openrc.md
      - Using OpenStack command line:
        - Managing SSH Keys: ui/cli/managing-ssh-keys.md
        - Setting up a Security Group: ui/cli/security_group.md
        - Setting up a Network: ui/cli/network.md
        - Launching a Virtual Machine: ui/cli/launch.md
        - Instance Management: ui/cli/manage.md
        - Deleting Infrastructure in the CLI: ui/cli/deleting.md
      - Storage Under the CLI: ui/cli/storage.md
      - Manila Shares in the CLI: ui/cli/manila.md
      - CLI Troubleshooting: ui/cli/troubleshooting.md
  - General VM Operations:
    - Security:
      - Firewalls: general/firewalls.md
    - Storage:
      - Manila:
        - Manila: general/manila.md
        - Using Manila Share on a VM: general/manilaVM.md
      - Object Store: general/object.md
      - File Transfer: general/filetransfer.md
    - Maintenance and Administration:
      - Add User to a VM: general/adduser.md
      - Installing Software on your VM: general/installsoftware.md
    - Software:
      - Jupyter on Jetstream2: general/jupyter.md
      - Galaxy: general/galaxy.md
  - Advanced Capabilities:
    - Containers on Jetstream2:
      - Docker: general/docker.md
      - Kubernetes: general/kubernetes.md
      - Build a K8s cluster: general/k8scluster.md
      - Managing Applications with Kubernetes: general/k8smanage.md
      - Persistent Volumes in Kubernetes: general/k8svolumes.md
      - Minikube: general/minikube.md
    - Terraform on Jetstream2: general/terraform.md
    - Virtual Clusters on Jetstream2: general/virtualclusters.md
